name: release

on:
  push:
    tags:
      - "*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: |
          mvn -v
          mvn clean package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.tgz

  build-linux-aarch64:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04

          # Not required, but speeds up builds by storing container images in
          # a GitHub package registry.
          githubToken: ${{ github.token }}

          run: |
            apt update && apt install openjdk-11-jdk -y
            ./mvnw clean package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.tgz

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn clean package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.tgz

  build-windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn clean package

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/*.tgz
